Base container
ArkCase/ark_prometheus_nodeexp pull request #1
Opened 2021-08-02 16:30 UTC by drivera-armedia

First version of the container to be merged to the main branch

2021-08-03 09:17 UTC, fabricetriboix requested changes

2021-08-03 09:17 UTC, fabricetriboix commented on Dockerfile
> +ARG ARCH="amd64"
Duplicate of line 1

2021-08-03 09:17 UTC, fabricetriboix commented on Dockerfile
> +ARG OS="linux"
Duplicate of line 2

2021-08-03 09:17 UTC, fabricetriboix commented on Dockerfile
> +		-o package.tar.gz && \
Same comment about S3 bucket and `get-artifcats.sh` as in the `ark_prometheus` PR

2021-08-03 09:17 UTC, fabricetriboix commented on Dockerfile
> +USER        nobody
Please create a user using `useradd` and do not use the `nobody` user

2021-08-03 09:17 UTC, fabricetriboix commented on Dockerfile
> +	chown nobody:nobody "/bin/node_exporter" && \
Please change this to `root:root`

2021-08-03 16:25 UTC, JonHolman requested changes

2021-08-03 16:25 UTC, JonHolman commented on Dockerfile
> +RUN curl \
add get-artifacts script, put this in our artifacts bucket

2021-08-03 16:25 UTC, JonHolman commented on Dockerfile
> +USER		nobody
As @fabricetriboix said on the other PR, please don't use nobody.  Create a user and use it.

2021-08-03 16:25 UTC, JonHolman commented on Dockerfile
> +ENTRYPOINT	[ "/bin/node_exporter" ]
as @fabricetriboix said on the other PR, please don't use ENTRYPOINT, use CMD

2021-08-10 08:27 UTC, fabricetriboix approved these changes, later dismissed

2021-08-10 08:27 UTC, fabricetriboix commented on Dockerfile
> +        MAINTAINER="Armedia LLC"
Not consistent with ark_prometheus

2021-08-10 14:58 UTC, fabricetriboix approved these changes

2021-08-12 15:47 UTC, JonHolman approved these changes

2021-08-12 15:47 UTC, JonHolman approved these changes

2021-08-20 19:52 UTC, merged